---
openapi: "3.0.0"
info:
  title: Rayan GPS API Documentation
  version: 1.1.0
  description:
    This is `RayanGPS.com/Panel` APIs documentation You can find out more about
    AVL at [RayanGPS.com](http://rayangps.com)

servers:
  - url: http://localhost:2001/api
    description: localhost
  - url: https://rayangps.com:3001/api
    description: HTTPS (Recommended)
  - url: http://rayangps.com:2001/api
    description: HTTP

tags:
  - name: Ticketing
    description: Ticketing system for users
    externalDocs:
      url: https://rayangps.com/panel/support/ticket

paths:
  /ticket:
    get:
      tags:
        - Ticketing
      operationId: getAllTicketsV1
      summary: returns all user tickets
      security:
        - jwtAuth: []
      responses:
        "200":
          description: |-
            OK
          content:
            application/json:
              examples:
                example1:
                  value:
                    [
                      {
                        "_id": "5de6aae019e4c13034af050d",
                        "title": "تیکت 1",
                        "application": "rayan_web",
                        "priority": 0,
                        "status": 1,
                        "user":
                          {
                            "_id": "5cea9a1f69ceb503e8358119",
                            "username": "rayan",
                          },
                        "number": 1003,
                        "__v": 0,
                      },
                      {
                        "_id": "5de6a15719e4c13034af050b",
                        "title": "تیکت 2",
                        "car": "5c49eb7586900f14686e85a7",
                        "application": "rayan_web",
                        "priority": 0,
                        "status": 0,
                        "user":
                          {
                            "_id": "5cea9a1f69ceb503e8358119",
                            "username": "rayan",
                          },
                        "number": 1002,
                        "__v": 0,
                      },
                    ]
        "404":
          description: |-
            404 Not found any ticket

  /ticket/{ticketId}:
    get:
      tags:
        - Ticketing
      operationId: getTicketV1
      summary: returns specified ticket
      security:
        - jwtAuth: []
      parameters:
        - in: path
          name: ticketId
          required: true
          schema:
            $ref: "#/components/schemas/general/properties/objectId"
          description: The ticket ID
      responses:
        "200":
          description: |-
            OK
          content:
            application/json:
              examples:
                example1:
                  value:
                    {
                      "_id": "5de6aae019e4c13034af050d",
                      "title": "تیکت 1",
                      "application": "rayan_web",
                      "priority": 0,
                      "status": 1,
                      "user":
                        {
                          "_id": "5cea9a1f69ceb503e8358119",
                          "username": "rayan",
                        },
                      "number": 1003,
                      "__v": 0,
                    }
        "404":
          description: |-
            404 Ticket not found (For specified user)
    put: # --- API ---
      tags:
        - Ticketing
      operationId: closeTicketV1
      summary: Changes ticket status to close
      security:
        - jwtAuth: []
      parameters:
        - in: path
          name: ticketId
          required: true
          schema:
            $ref: "#/components/schemas/general/properties/objectId"
          description: The ticket ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                closeTicket:
                  type: boolean
            example:
              closeTicket: true
      responses:
        "200":
          description: |-
            OK
        "404":
          description: |-
            404 Ticket not found (For specified user)

  /ticket/new:
    post:
      tags:
        - Ticketing
      operationId: newTicketV1
      summary: Inserts new ticket
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: true
                priority:
                  $ref: "#/components/schemas/ticket/properties/priorities"
                application:
                  $ref: "#/components/schemas/general/properties/application_type"
                car:
                  $ref: "#/components/schemas/general/properties/objectId"
                text:
                  type: string
            example:
              title: عنوان تیکت/موضوع تیکت'
              priority: 0
              application: rayan_android
              car: 5db6a6383612da23a4e76a4e
              text: متن توضیحات تیکت
      responses:
        "200":
          description: |-
            OK
        "400":
          description: |-
            Bad request
  /ticket/newMessage:
    post:
      tags:
        - Ticketing
      operationId: newMessageV1
      summary: Inserts new ticket message
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ticketId:
                  $ref: "#/components/schemas/general/properties/objectId"
                text:
                  type: string
            example:
              ticketId: 5db6a6383612da23a4e76a4e
              text: متن توضیحات پیام
      responses:
        "200":
          description: |-
            OK
        "404":
          description: |-
            Ticket not found
        "400":
          description: |-
            Bad request

components:
  schemas:
    general:
      title: General
      type: object
      properties:
        application_type:
          type: string
          enum: [rayan_web, rayan_android]
          required: true
        objectId:
          type: string
          minimum: 24
          maximum: 24
    ticket:
      title: Ticket enums
      type: object
      properties:
        status:
          type: number
          enum: [0, 1, 2]
          required: true
          description: "0: userRespone (درحال بررسی) <br/> 1: operatorRespone (پاسخ داده شده) <br/> 3: closed (بسته شده)"
        priorities:
          type: number
          enum: [0, 1, 2]
          required: true
          description: "0: low (کم) <br/> 1: medium (متوسط) <br/> 3: high (زیاد)"

  securitySchemes:
    jwtAuth:
      type: apiKey
      in: header
      name: x-auth-token
